#!/bin/bash
# AI Features Testing Commands - All-in-One
# Copy-paste these commands into Terminal 3 for testing
# Date: 2026-05-15

echo "════════════════════════════════════════════════════════════════"
echo "AI FEATURES TESTING - COPY-PASTE COMMANDS"
echo "════════════════════════════════════════════════════════════════"

# ================================================================
# SECTION 1: SETUP & PREREQUISITES
# ================================================================

echo ""
echo "═══ STEP 1: VERIFY SETUP ═══"
echo ""
echo "# 1.1 Check Python service is running"
echo "curl http://localhost:5000/api/ai/health | python -m json.tool"
echo ""
echo "# 1.2 Check Java backend is running"
echo "curl http://localhost:8080/api/players/ai/health | python -m json.tool"
echo ""

# ================================================================
# SECTION 2: TRAIN ML MODELS (ONE TIME)
# ================================================================

echo "═══ STEP 2: TRAIN ML MODELS (ONE TIME ONLY) ═══"
echo ""
echo "cd d:\PI2027\PI_StreetLeague\ai-service"
echo "python train_player_prediction_model.py"
echo ""
echo "# Watch for:"
echo "# ✓ [Training] Loaded 50 samples from CSV"
echo "# ✓ [Training] R² Score: 0.88"
echo "# ✓ [Export] Model exported successfully"
echo ""

# ================================================================
# SECTION 3: FEATURE 1 - PLAYER PERFORMANCE PREDICTION
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "FEATURE 1: PLAYER PERFORMANCE PREDICTION (Future Performance)"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "═══ TEST 1.1: CUSTOM PREDICTION (Strong Attacker) ═══"
echo ""
echo "curl -X POST http://localhost:8080/api/players/ai-predict-custom \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"playerId\": 101,"
echo "    \"goals\": 3,"
echo "    \"assists\": 2,"
echo "    \"tackles\": 5,"
echo "    \"interceptions\": 3,"
echo "    \"passesCompleted\": 52,"
echo "    \"passAccuracy\": 87.5,"
echo "    \"distanceCoveredKm\": 10.5,"
echo "    \"averageSpeedKmh\": 25.8,"
echo "    \"ballPossessionPercent\": 51.0,"
echo "    \"foulsCommitted\": 1,"
echo "    \"shotsOnTarget\": 4"
echo "  }' | python -m json.tool"
echo ""
echo "Expected: Rating ~76.5 (EXCELLENT), HIGH confidence"
echo ""

echo "═══ TEST 1.2: CUSTOM PREDICTION (Defensive Midfielder) ═══"
echo ""
echo "curl -X POST http://localhost:8080/api/players/ai-predict-custom \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"playerId\": 102,"
echo "    \"goals\": 0,"
echo "    \"assists\": 1,"
echo "    \"tackles\": 9,"
echo "    \"interceptions\": 7,"
echo "    \"passesCompleted\": 58,"
echo "    \"passAccuracy\": 91.5,"
echo "    \"distanceCoveredKm\": 11.8,"
echo "    \"averageSpeedKmh\": 26.5,"
echo "    \"ballPossessionPercent\": 52.0,"
echo "    \"foulsCommitted\": 1,"
echo "    \"shotsOnTarget\": 0"
echo "  }' | python -m json.tool"
echo ""
echo "Expected: Rating ~72+ (GOOD), HIGH confidence, strengths=defense"
echo ""

echo "═══ TEST 1.3: CUSTOM PREDICTION (Poor Performance) ═══"
echo ""
echo "curl -X POST http://localhost:8080/api/players/ai-predict-custom \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"playerId\": 103,"
echo "    \"goals\": 0,"
echo "    \"assists\": 0,"
echo "    \"tackles\": 2,"
echo "    \"interceptions\": 1,"
echo "    \"passesCompleted\": 35,"
echo "    \"passAccuracy\": 70.0,"
echo "    \"distanceCoveredKm\": 7.2,"
echo "    \"averageSpeedKmh\": 20.5,"
echo "    \"ballPossessionPercent\": 38.0,"
echo "    \"foulsCommitted\": 4,"
echo "    \"shotsOnTarget\": 0"
echo "  }' | python -m json.tool"
echo ""
echo "Expected: Rating <50 (BAD/AVERAGE), LOW confidence, many weaknesses"
echo ""

echo "═══ TEST 1.4: BATCH PREDICTION (Multiple Players) ═══"
echo ""
echo "curl -X POST http://localhost:8080/api/players/ai-predict-batch \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '[{"
echo "    \"playerId\": 1, \"goals\": 3, \"assists\": 2, \"tackles\": 5,"
echo "    \"interceptions\": 3, \"passesCompleted\": 52, \"passAccuracy\": 87.5,"
echo "    \"distanceCoveredKm\": 10.5, \"averageSpeedKmh\": 25.8,"
echo "    \"ballPossessionPercent\": 51.0, \"foulsCommitted\": 1, \"shotsOnTarget\": 4"
echo "  }, {"
echo "    \"playerId\": 2, \"goals\": 1, \"assists\": 0, \"tackles\": 8,"
echo "    \"interceptions\": 6, \"passesCompleted\": 56, \"passAccuracy\": 90.2,"
echo "    \"distanceCoveredKm\": 11.2, \"averageSpeedKmh\": 26.5,"
echo "    \"ballPossessionPercent\": 48.0, \"foulsCommitted\": 3, \"shotsOnTarget\": 1"
echo "  }, {"
echo "    \"playerId\": 3, \"goals\": 2, \"assists\": 1, \"tackles\": 4,"
echo "    \"interceptions\": 2, \"passesCompleted\": 49, \"passAccuracy\": 84.3,"
echo "    \"distanceCoveredKm\": 9.8, \"averageSpeedKmh\": 24.5,"
echo "    \"ballPossessionPercent\": 50.0, \"foulsCommitted\": 2, \"shotsOnTarget\": 3"
echo "  }]' | python -m json.tool"
echo ""
echo "Expected: 3 predictions with different ratings"
echo ""

echo "═══ TEST 1.5: AI SERVICE HEALTH ═══"
echo ""
echo "curl http://localhost:5000/api/ai/health | python -m json.tool"
echo ""
echo "Expected: player_prediction_model_loaded = true"
echo ""

# ================================================================
# SECTION 4: FEATURE 2 - ADVANCED MÉTIER 1 (BASIC PREDICTION)
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "FEATURE 2: ADVANCED MÉTIER 1 - BASIC PREDICTION"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "═══ TEST 2.1: GET BASIC PREDICTION (Player 1) ═══"
echo ""
echo "curl http://localhost:8080/api/players/1/prediction | python -m json.tool"
echo ""
echo "Expected:"
echo "  - predictedPerformanceRating: ~72.5"
echo "  - performanceCategory: GOOD"
echo "  - reliability: > 70%"
echo "  - trendDirection: IMPROVING/STABLE/DECLINING"
echo ""

echo "═══ TEST 2.2: GET BASIC PREDICTIONS (Multiple Players) ═══"
echo ""
echo "for i in 1 2 3 4 5; do"
echo "  echo \"\";"
echo "  echo \"=== PLAYER \$i ===\";"
echo "  curl http://localhost:8080/api/players/\$i/prediction | python -m json.tool | grep -E 'playerId|predictedPerformanceRating|performanceCategory|trendDirection';"
echo "done"
echo ""
echo "Expected: Different predictions for each player"
echo ""

echo "═══ TEST 2.3: VERIFY TREND DIRECTION ═══"
echo ""
echo "# If player is improving:"
echo "curl http://localhost:8080/api/players/1/prediction | python -m json.tool | grep trendDirection"
echo ""
echo "Expected: trendDirection = 'IMPROVING' (recent form > historical average)"
echo ""

# ================================================================
# SECTION 5: FEATURE 3 - ADVANCED MÉTIER 2 (ADVANCED AI)
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "FEATURE 3: ADVANCED MÉTIER 2 - ADVANCED AI PREDICTION"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "═══ TEST 3.1: COMPARE BASIC VS AI PREDICTION ═══"
echo ""
echo "curl http://localhost:8080/api/players/1/ai-prediction | python -m json.tool"
echo ""
echo "Expected:"
echo "  - basicPrediction.rating: e.g., 72.5"
echo "  - aiPrediction.rating: e.g., 76.5"
echo "  - comparison.ratingDifference: 4.0"
echo "  - explanation: why they differ"
echo ""

echo "═══ TEST 3.2: ANALYZE STRENGTHS/WEAKNESSES ═══"
echo ""
echo "curl http://localhost:8080/api/players/1/ai-prediction | python -m json.tool | grep -A5 'strengths\\|weaknesses'"
echo ""
echo "Expected: List of specific strengths (attack, defense, etc.)"
echo ""

echo "═══ TEST 3.3: CHECK CONFIDENCE LEVELS ═══"
echo ""
echo "curl http://localhost:8080/api/players/1/ai-prediction | python -m json.tool | grep confidence"
echo ""
echo "Expected: confidence = 'HIGH' or 'MEDIUM' or 'LOW'"
echo ""

# ================================================================
# SECTION 6: BROWSER CONSOLE TESTS (F12 → Console)
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "BROWSER CONSOLE TESTS (Open DevTools: F12)"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "═══ CONSOLE TEST 1: Basic Table View ═══"
echo ""
echo "fetch('http://localhost:8080/api/players/1/prediction')"
echo "  .then(r => r.json())"
echo "  .then(d => console.table(d.prediction))"
echo ""

echo "═══ CONSOLE TEST 2: AI vs Basic Comparison ═══"
echo ""
echo "fetch('http://localhost:8080/api/players/1/ai-prediction')"
echo "  .then(r => r.json())"
echo "  .then(d => {"
echo "    console.log('=== BASIC PREDICTION ===');"
echo "    console.table(d.basicPrediction);"
echo "    console.log('=== AI PREDICTION ===');"
echo "    console.table(d.aiPrediction);"
echo "    console.log('=== COMPARISON ===');"
echo "    console.table(d.comparison);"
echo "  })"
echo ""

echo "═══ CONSOLE TEST 3: Custom Prediction ═══"
echo ""
echo "fetch('http://localhost:8080/api/players/ai-predict-custom', {"
echo "  method: 'POST',"
echo "  headers: { 'Content-Type': 'application/json' },"
echo "  body: JSON.stringify({"
echo "    playerId: 101, goals: 3, assists: 2, tackles: 5,"
echo "    interceptions: 3, passesCompleted: 52, passAccuracy: 87.5,"
echo "    distanceCoveredKm: 10.5, averageSpeedKmh: 25.8,"
echo "    ballPossessionPercent: 51.0, foulsCommitted: 1, shotsOnTarget: 4"
echo "  })"
echo "})"
echo "  .then(r => r.json())"
echo "  .then(d => console.table(d))"
echo ""

# ================================================================
# SECTION 7: DEBUG COMMANDS
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "DEBUG & TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "═══ DEBUG 1: Check if ports are in use ═══"
echo ""
echo "lsof -i :5000     # Python service"
echo "lsof -i :8080     # Java backend"
echo ""

echo "═══ DEBUG 2: Kill stuck processes ═══"
echo ""
echo "lsof -i :5000 | awk 'NR==2 {print \$2}' | xargs kill -9"
echo "lsof -i :8080 | awk 'NR==2 {print \$2}' | xargs kill -9"
echo ""

echo "═══ DEBUG 3: Verify model files exist ═══"
echo ""
echo "ls -la d:\PI2027\PI_StreetLeague\ai-service\model\"
echo ""
echo "Expected files:"
echo "  - player_performance_model.joblib"
echo "  - player_performance_scaler.joblib"
echo "  - player_performance_feature_names.joblib"
echo "  - player_performance_metadata.joblib"
echo ""

echo "═══ DEBUG 4: Verify CSV dataset exists ═══"
echo ""
echo "ls -la d:\PI2027\PI_StreetLeague\ai-service\data\player_performance_dataset.csv"
echo ""
echo "head -5 d:\PI2027\PI_StreetLeague\ai-service\data\player_performance_dataset.csv"
echo ""

echo "═══ DEBUG 5: Retrain models from scratch ═══"
echo ""
echo "cd d:\PI2027\PI_StreetLeague\ai-service"
echo "python train_player_prediction_model.py"
echo ""

# ================================================================
# SECTION 8: FULL TEST SUITE
# ================================================================

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "COMPLETE TEST SEQUENCE (Copy all and paste into Terminal 3)"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "echo \"Testing Feature 1...\" && \\"
echo "curl -X POST http://localhost:8080/api/players/ai-predict-custom \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"playerId\":101,\"goals\":3,\"assists\":2,\"tackles\":5,\"interceptions\":3,\"passesCompleted\":52,\"passAccuracy\":87.5,\"distanceCoveredKm\":10.5,\"averageSpeedKmh\":25.8,\"ballPossessionPercent\":51.0,\"foulsCommitted\":1,\"shotsOnTarget\":4}' | python -m json.tool && \\"
echo ""
echo "echo \"Testing Feature 2...\" && \\"
echo "curl http://localhost:8080/api/players/1/prediction | python -m json.tool && \\"
echo ""
echo "echo \"Testing Feature 3...\" && \\"
echo "curl http://localhost:8080/api/players/1/ai-prediction | python -m json.tool"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ TESTING COMPLETE!"
echo "════════════════════════════════════════════════════════════════"
