sonar.projectKey=PI_StreetLeague
sonar.projectName=PI StreetLeague
sonar.host.url=http://host.docker.internal:9000
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*DTO.java,**/*MapperImpl.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=false
