apiVersion: v1
kind: ConfigMap
metadata:
  name: streetleague-config
  namespace: pi-streetleague
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/streetleague?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  APP_JWT_EXPIRATION_SECONDS: "86400"
  SERVER_PORT: "18080"
  OLLAMA_URL: "http://host.docker.internal:11434"
  OLLAMA_MODEL: "llama3"
  APP_EMAIL_ENABLED: "false"
  WEATHER_API_ENABLED: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
