apiVersion: v1
kind: Secret
metadata:
  name: streetleague-secrets
  namespace: pi-streetleague
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
  APP_JWT_SECRET: c3RyZWV0bGVhZ3VlLWxvY2FsLWRldmVsb3BtZW50LXNlY3JldC1jaGFuZ2UtYmVmb3JlLXByb2Q=
  WEATHER_API_KEY: YWJhYjcxYTM1NGM0YWRjOTU5OWQxZDFmYWNjZTViZDQ=
